package com.ccc.ui.widgets.gwt.menu;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.VerticalLayout;

public class OptionsPane extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private VerticalLayout wrapperLayout;
	@AutoGenerated
	private VerticalLayout linksLayout;
	@AutoGenerated
	private VerticalLayout accountManagementBackground;
	@AutoGenerated
	private VerticalLayout broadCastLinkBackground;
	@AutoGenerated
	private VerticalLayout accountActivityBackground;
	@AutoGenerated
	private Button importContacts;
	@AutoGenerated
	private Button sendMessageButton;
	@AutoGenerated
	private Button accountManagement;
	@AutoGenerated
	private Embedded logoImg;


	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


	


	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


	


	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


	



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	
	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public OptionsPane() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}


	public Button getSendButton() {
		return sendMessageButton;
	}
	
	
	
	public Button accountManagementButton() {
		return accountManagement;
		
	}
	
	public Button getImportButton() {
		return importContacts;
	}
	
	
	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("220px");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("220px");
		setHeight("100.0%");
		
		// wrapperLayout
		wrapperLayout = buildWrapperLayout();
		mainLayout.addComponent(wrapperLayout, "top:0.0px;left:20.0px;");
		
		return mainLayout;
	}


	@AutoGenerated
	private VerticalLayout buildWrapperLayout() {
		// common part: create layout
		wrapperLayout = new VerticalLayout();
		wrapperLayout.setImmediate(false);
		wrapperLayout.setWidth("200px");
		wrapperLayout.setHeight("500px");
		wrapperLayout.setMargin(false);
		
		// linksLayout
		linksLayout = buildLinksLayout();
		wrapperLayout.addComponent(linksLayout);
		
		return wrapperLayout;
	}


	@AutoGenerated
	private VerticalLayout buildLinksLayout() {
		// common part: create layout
		linksLayout = new VerticalLayout();
		linksLayout.setStyleName("insetBackground");
		linksLayout.setImmediate(false);
		linksLayout.setWidth("175px");
		linksLayout.setHeight("400px");
		linksLayout.setMargin(false);
		linksLayout.setSpacing(true);
		
		// logoImg
		logoImg = new Embedded();
		logoImg.setImmediate(false);
		logoImg.setWidth("50px");
		logoImg.setHeight("50px");
		logoImg.setSource(new ThemeResource("img/logo.jpg"));
		logoImg.setType(1);
		logoImg.setMimeType("image/png");
		linksLayout.addComponent(logoImg);
		
		// accountManagement
		accountManagement = new Button();
		accountManagement.setCaption("Account Management");
		accountManagement.setImmediate(true);
		accountManagement.setWidth("160px");
		accountManagement.setHeight("-1px");
		linksLayout.addComponent(accountManagement);
		
		// sendMessageButton
		sendMessageButton = new Button();
		sendMessageButton.setCaption("Send Messages");
		sendMessageButton.setImmediate(true);
		sendMessageButton.setWidth("160px");
		sendMessageButton.setHeight("-1px");
		linksLayout.addComponent(sendMessageButton);
		
		// importContacts
		importContacts = new Button();
		importContacts.setCaption("Import Contacts");
		importContacts.setImmediate(true);
		importContacts.setWidth("160px");
		importContacts.setHeight("-1px");
		linksLayout.addComponent(importContacts);
		
		// accountActivityBackground
		accountActivityBackground = new VerticalLayout();
		accountActivityBackground.setStyleName("linkbackground");
		accountActivityBackground.setImmediate(false);
		accountActivityBackground.setWidth("-1px");
		accountActivityBackground.setHeight("-1px");
		accountActivityBackground.setMargin(false);
		linksLayout.addComponent(accountActivityBackground);
		
		// broadCastLinkBackground
		broadCastLinkBackground = new VerticalLayout();
		broadCastLinkBackground.setStyleName("linkbackground");
		broadCastLinkBackground.setImmediate(false);
		broadCastLinkBackground.setWidth("-1px");
		broadCastLinkBackground.setHeight("-1px");
		broadCastLinkBackground.setMargin(false);
		linksLayout.addComponent(broadCastLinkBackground);
		
		// accountManagementBackground
		accountManagementBackground = new VerticalLayout();
		accountManagementBackground.setStyleName("linkbackground");
		accountManagementBackground.setImmediate(false);
		accountManagementBackground.setWidth("-1px");
		accountManagementBackground.setHeight("-1px");
		accountManagementBackground.setMargin(false);
		linksLayout.addComponent(accountManagementBackground);
		
		return linksLayout;
	}
}
