package com.ccc.ui.widgets.messages.publishing;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.DependsOn;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import org.vaadin.openesignforms.ckeditor.CKEditorConfig;
import org.vaadin.openesignforms.ckeditor.CKEditorTextField;

import com.ccc.mail.mailinglist.model.MailingList;
import com.ccc.ui.widgets.analytics.AnalyticsDashBoard;
import com.ccc.ui.widgets.gwt.mail.ManageMailingAccount;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.InlineDateField;
import com.vaadin.ui.Label;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TabSheet.Tab;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.TwinColSelect;
import com.vaadin.ui.Upload;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.VerticalSplitPanel;
@Component
@Scope("session")
@DependsOn("appSyc")

public class AppWidget extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button logoutButton;
	@AutoGenerated
	private TabSheet richEmail;
	@AutoGenerated
	private VerticalLayout simpleSendContainer;
	@AutoGenerated
	private VerticalLayout verticalLayout_10;
	@AutoGenerated
	private VerticalLayout verticalLayout_7;
	@AutoGenerated
	private VerticalLayout verticalLayout_11;
	@AutoGenerated
	private TextArea simpleSendTextArea;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_3;
	@AutoGenerated
	private Button simpleSendButton;
	@AutoGenerated
	private Button saveSimpleDraftButton;
	@AutoGenerated
	private ListSelect simpleAttachmentSelect;
	@AutoGenerated
	private Upload simpleAttachment;
	@AutoGenerated
	private TextField simpleSendSubjectText;
	@AutoGenerated
	private VerticalLayout richEmailLayout;
	@AutoGenerated
	private VerticalLayout richEmailWrapper;
	@AutoGenerated
	private VerticalLayout bottomLayout;
	@AutoGenerated
	private HorizontalLayout sendRichWrapper;
	@AutoGenerated
	private Button saveRichTabButton;
	@AutoGenerated
	private Button sendRichEmail;
	@AutoGenerated
	private ListSelect richFileAttachmentSelect;
	@AutoGenerated
	private Upload addAttachment;
	@AutoGenerated
	private CKEditorTextField cKEditorTextField_1;
	@AutoGenerated
	private HorizontalLayout subjectWrapperLayout;
	@AutoGenerated
	private TextField subjectTextField;
	@AutoGenerated
	private TabSheet mailingListTab;
	@AutoGenerated
	private AnalyticsDashBoard analyticsDashBoard;
	@AutoGenerated
	private VerticalLayout sendMessages;
	@AutoGenerated
	private VerticalSplitPanel verticalSplitPanel_1;
	@AutoGenerated
	private HorizontalLayout messageManagementTab;
	@AutoGenerated
	private Button deleteDraftButton;
	@AutoGenerated
	private Button editDraftButton;
	@AutoGenerated
	private ListSelect draftListSelect;
	@AutoGenerated
	private Button deleteTimedMessageButton;
	@AutoGenerated
	private Button editTimedMessageButton;
	@AutoGenerated
	private ListSelect sentMessagesSelect;
	@AutoGenerated
	private HorizontalSplitPanel horizontalSplitPanel_1;
	@AutoGenerated
	private VerticalLayout timedMessagePanel;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private Button schedulePost;
	@AutoGenerated
	private InlineDateField inlineDateField_1;
	@AutoGenerated
	private Label timedMessage;
	@AutoGenerated
	private TwinColSelect messageSendingColSelect;
	@AutoGenerated
	private VerticalLayout facebookContainer;
	@AutoGenerated
	private HorizontalSplitPanel horizontalSplitPanel_2;
	@AutoGenerated
	private VerticalSplitPanel facebookPanel;
	@AutoGenerated
	private VerticalLayout facebookPanelBottom;
	@AutoGenerated
	private Label inactiveFacebookLabel;
	@AutoGenerated
	private VerticalLayout facebookPanelTop;
	@AutoGenerated
	private Label activeFacebookLabel;
	@AutoGenerated
	private VerticalLayout verticalLayout_5;
	@AutoGenerated
	private Button deleteFacebookButton;
	@AutoGenerated
	private ListSelect facebookAccountSelect;
	@AutoGenerated
	private Button openFacebook;
	@AutoGenerated
	private Button importFacebookButton;
	@AutoGenerated
	private VerticalLayout twitterLayout;
	@AutoGenerated
	private HorizontalSplitPanel horizontalSplitPanel_3;
	@AutoGenerated
	private VerticalSplitPanel twitterPanel;
	@AutoGenerated
	private VerticalLayout twitterPanelBottom;
	@AutoGenerated
	private Label disabledTwitterAccountsLabel;
	@AutoGenerated
	private VerticalLayout twitterPanelTop;
	@AutoGenerated
	private VerticalLayout verticalLayout_3;
	@AutoGenerated
	private Button deleteTwitterButton;
	@AutoGenerated
	private ListSelect twitterSelectList;
	@AutoGenerated
	private Button openTwitterButton;
	@AutoGenerated
	private VerticalLayout mailingListContainer;
	@AutoGenerated
	private ManageMailingAccount manageMailingAccount_2;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private List<File> simpleAttachments = new ArrayList<File>();
	private List<File> richAttachments = new ArrayList<File>();

	private static Logger log=LoggerFactory.getLogger(AppWidget.class);
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */




	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	public TextField getRichSubjectTextField() {
		return subjectTextField;
	}

	public VerticalSplitPanel getFacebookPanel() {
		return facebookPanel;
	}

	public void setFacebookPanel(VerticalSplitPanel facebookPanel) {
		this.facebookPanel = facebookPanel;
	}

	public VerticalSplitPanel getTwitterPanel() {
		return twitterPanel;
	}

	public void setTwitterPanel(VerticalSplitPanel twitterPanel) {
		this.twitterPanel = twitterPanel;
	}

	public TextField getSimpleSendSubjectText() {
		return simpleSendSubjectText;
	}

	public void setSimpleSendSubjectText(TextField simpleSendSubjectText) {
		this.simpleSendSubjectText = simpleSendSubjectText;
	}

	public TextField getSubjectTextField() {
		return subjectTextField;
	}

	public void setSubjectTextField(TextField subjectTextField) {
		this.subjectTextField = subjectTextField;
	}

	public HorizontalLayout getMessageManagementTab() {
		return messageManagementTab;
	}

	public Button getLogoutButton() {
		return logoutButton;
	}

	public void setLogoutButton(Button logoutButton) {
		this.logoutButton = logoutButton;
	}

	public void setMessageManagementTab(HorizontalLayout messageManagementTab) {
		this.messageManagementTab = messageManagementTab;
	}

	public Button getDeleteDraftButton() {
		return deleteDraftButton;
	}

	public void setDeleteDraftButton(Button deleteDraftButton) {
		this.deleteDraftButton = deleteDraftButton;
	}

	public Button getEditDraftButton() {
		return editDraftButton;
	}

	public void setEditDraftButton(Button editDraftButton) {
		this.editDraftButton = editDraftButton;
	}

	public ListSelect getDraftListSelect() {
		return draftListSelect;
	}

	public void setDraftListSelect(ListSelect draftListSelect) {
		this.draftListSelect = draftListSelect;
	}

	public Button getSchedulePost() {
		return schedulePost;
	}

	public void setSchedulePost(Button schedulePost) {
		this.schedulePost = schedulePost;
	}

	public Button getDeleteTimedMessageButton() {
		return deleteTimedMessageButton;
	}

	public void setDeleteTimedMessageButton(Button deleteTimedMessageButton) {
		this.deleteTimedMessageButton = deleteTimedMessageButton;
	}

	public Button getEditTimedMessageButton() {
		return editTimedMessageButton;
	}

	public void setEditTimedMessageButton(Button editTimedMessageButton) {
		this.editTimedMessageButton = editTimedMessageButton;
	}

	public ListSelect getSentMessagesSelect() {
		return sentMessagesSelect;
	}

	public void setSentMessagesSelect(ListSelect sentMessagesSelect) {
		this.sentMessagesSelect = sentMessagesSelect;
	}

	public TextField getSimpleSendTextField() {
		return simpleSendSubjectText;
	}

	public Button getSimpleSendButton() {
		return simpleSendButton;
	}


	public Button getOpenFacebook() {
		return openFacebook;
	}


	public void setOpenFacebook(Button openFacebook) {
		this.openFacebook = openFacebook;
	}




	public Button getOpenTwitterButton() {
		return openTwitterButton;
	}


	public void setOpenTwitterButton(Button openTwitterButton) {
		this.openTwitterButton = openTwitterButton;
	}


	public Button getImportFacebookButton() {
		return importFacebookButton;
	}





	public void setImportFacebookButton(Button importFacebookButton) {
		this.importFacebookButton = importFacebookButton;
	}


	public void setSimpleSendButton(Button simpleSendButton) {
		this.simpleSendButton = simpleSendButton;
	}





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */







	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	private void setTabColors() {
		Tab richEmailTab=richEmail.getTab(richEmailLayout);
		Tab simpleSendTab=richEmail.getTab(simpleSendContainer);
		Tab facebookTab=mailingListTab.getTab(facebookContainer);
		Tab twitterTab=mailingListTab.getTab(twitterLayout);
		Tab mailingLists=mailingListTab.getTab(mailingListContainer);
		
		Tab[] tabs={richEmailTab,simpleSendTab,facebookTab,twitterTab,mailingLists};
		for(Tab tab : tabs) {
			tab.setStyleName("tabbackground");
		}
	}

	public TwinColSelect getMessageSendingColSelect() {
		return messageSendingColSelect;
	}



	public ListSelect getSimpleAttachmentSelect() {
		return simpleAttachmentSelect;
	}

	public void setSimpleAttachmentSelect(ListSelect simpleAttachmentSelect) {
		this.simpleAttachmentSelect = simpleAttachmentSelect;
	}

	public ListSelect getRichFileAttachmentSelect() {
		return richFileAttachmentSelect;
	}

	public void setRichFileAttachmentSelect(ListSelect richFileAttachmentSelect) {
		this.richFileAttachmentSelect = richFileAttachmentSelect;
	}

	public void setMessageSendingColSelect(TwinColSelect messageSendingColSelect) {
		this.messageSendingColSelect = messageSendingColSelect;
	}





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


	public Button getDeleteFacebookButton() {
		return deleteFacebookButton;
	}

	public VerticalLayout getFacebookPanelBottom() {
		return facebookPanelBottom;
	}

	public void setFacebookPanelBottom(VerticalLayout facebookPanelBottom) {
		this.facebookPanelBottom = facebookPanelBottom;
	}

	public VerticalLayout getFacebookPanelTop() {
		return facebookPanelTop;
	}

	public void setFacebookPanelTop(VerticalLayout facebookPanelTop) {
		this.facebookPanelTop = facebookPanelTop;
	}

	public VerticalLayout getTwitterPanelBottom() {
		return twitterPanelBottom;
	}

	public void setTwitterPanelBottom(VerticalLayout twitterPanelBottom) {
		this.twitterPanelBottom = twitterPanelBottom;
	}

	public VerticalLayout getTwitterPanelTop() {
		return twitterPanelTop;
	}

	public void setTwitterPanelTop(VerticalLayout twitterPanelTop) {
		this.twitterPanelTop = twitterPanelTop;
	}

	public void setDeleteFacebookButton(Button deleteFacebookButton) {
		this.deleteFacebookButton = deleteFacebookButton;
	}

	public ListSelect getFacebookAccountSelect() {
		return facebookAccountSelect;
	}

	public void setFacebookAccountSelect(ListSelect facebookAccountSelect) {
		this.facebookAccountSelect = facebookAccountSelect;
	}

	public Button getDeleteTwitterButton() {
		return deleteTwitterButton;
	}

	public void setDeleteTwitterButton(Button deleteTwitterButton) {
		this.deleteTwitterButton = deleteTwitterButton;
	}

	public ListSelect getTwitterSelectList() {
		return twitterSelectList;
	}

	public void setTwitterSelectList(ListSelect twitterSelectList) {
		this.twitterSelectList = twitterSelectList;
	}

	public Button getScheduledPost() {
		return schedulePost;
	}

	public VerticalLayout getTimedMessagePanel() {
		return timedMessagePanel;
	}


	public ManageMailingAccount getManageMailingAccount_2() {
		return manageMailingAccount_2;
	}


	public void setManageMailingAccount_2(
			ManageMailingAccount manageMailingAccount_2) {
		this.manageMailingAccount_2 = manageMailingAccount_2;
	}


	public void setTimedMessagePanel(VerticalLayout timedMessagePanel) {
		this.timedMessagePanel = timedMessagePanel;
	}





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	public AnalyticsDashBoard getAnalyticsDashBoard() {
		return analyticsDashBoard;
	}

	public void setAnalyticsDashBoard(AnalyticsDashBoard analyticsDashBoard) {
		this.analyticsDashBoard = analyticsDashBoard;
	}

	public Button getSaveSimpleDraftButton() {
		return saveSimpleDraftButton;
	}

	public void setSaveSimpleDraftButton(Button saveSimpleDraftButton) {
		this.saveSimpleDraftButton = saveSimpleDraftButton;
	}

	public Button getSaveRichTabButton() {
		return saveRichTabButton;
	}

	public void setSaveRichTabButton(Button saveRichTabButton) {
		this.saveRichTabButton = saveRichTabButton;
	}

	

	public TabSheet getMailingListTab() {
		return mailingListTab;
	}


	public void setMailingListTab(TabSheet mailingListTab) {
		this.mailingListTab = mailingListTab;
	}


	public VerticalLayout getSendMessages() {
		return sendMessages;
	}


	public void setSendMessages(VerticalLayout sendMessages) {
		this.sendMessages = sendMessages;
	}


	public Upload getSimpleAttachment() {
		return simpleAttachment;
	}


	public void setSimpleAttachment(Upload simpleAttachment) {
		this.simpleAttachment = simpleAttachment;
	}






	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


	public TabSheet getRichEmail() {
		return richEmail;
	}


	public void setRichEmail(TabSheet richEmail) {
		this.richEmail = richEmail;
	}


	public TextArea getSimpleSendTextArea() {
		return simpleSendTextArea;
	}


	public void setSimpleSendTextArea(TextArea simpleSendTextArea) {
		this.simpleSendTextArea = simpleSendTextArea;
	}




	public Button getSendRichEmail() {
		return sendRichEmail;
	}


	public void setSendRichEmail(Button sendRichEmail) {
		this.sendRichEmail = sendRichEmail;
	}


	public Upload getAddAttachment() {
		return addAttachment;
	}


	public void setAddAttachment(Upload addAttachment) {
		this.addAttachment = addAttachment;
	}


	public CKEditorTextField getcKEditorTextField_1() {
		return cKEditorTextField_1;
	}


	public void setcKEditorTextField_1(CKEditorTextField cKEditorTextField_1) {
		this.cKEditorTextField_1 = cKEditorTextField_1;
	}


	public InlineDateField getInlineDateField_1() {
		return inlineDateField_1;
	}


	public void setInlineDateField_1(InlineDateField inlineDateField_1) {
		this.inlineDateField_1 = inlineDateField_1;
	}


	public Label getTimedMessage() {
		return timedMessage;
	}


	public void setTimedMessage(Label timedMessage) {
		this.timedMessage = timedMessage;
	}

	public List<File> getRichAttachments() {
		return richAttachments;
	}

	public List<File> getSimpleAttachments() {
		return simpleAttachments;
	}




	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */





	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */




	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */




	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public AppWidget() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		CKEditorConfig config = new CKEditorConfig();
		config.useCompactTags();
		config.disableElementsPath();
		config.setResizeDir(CKEditorConfig.RESIZE_DIR.HORIZONTAL);
		config.disableSpellChecker();
		config.setToolbarCanCollapse(false);
		config.setWidth("100%");
		config.setHeight("500px");
		this.cKEditorTextField_1.setConfig(config);
		Tab facebookTab=mailingListTab.getTab(facebookContainer);
		Tab mailingList=mailingListTab.getTab(mailingListContainer);
		Tab twitterTab=mailingListTab.getTab(twitterLayout);
		facebookTab.setIcon(new ThemeResource("img/smallfacebook.jpg"));
		mailingList.setIcon(new ThemeResource("img/small_mail.gif"));
		twitterTab.setIcon(new ThemeResource("img/smalltwitter.jpg"));
		setTabColors();
		draftListSelect.setImmediate(true);
		manageMailingAccount_2.getMailingListSelect().addListener(new ListSelect.ValueChangeListener() {


			@Override
			public void valueChange(
					com.vaadin.data.Property.ValueChangeEvent event) {
				Property prop=event.getProperty();
				MailingList list=(MailingList) prop.getValue();	
				messageSendingColSelect.addItem(list);
			}

		});
	}

	public InlineDateField getSentDateField() {
		return inlineDateField_1;
	}
	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setStyleName("background");
		mainLayout.setImmediate(false);
		mainLayout.setWidth("1600px");
		mainLayout.setHeight("800px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("1600px");
		setHeight("800px");
		
		// mailingListTab
		mailingListTab = buildMailingListTab();
		mainLayout.addComponent(mailingListTab, "top:40.0px;left:0.0px;");
		
		// richEmail
		richEmail = buildRichEmail();
		mainLayout.addComponent(richEmail, "top:0.0px;right:0.0px;");
		
		// logoutButton
		logoutButton = new Button();
		logoutButton.setCaption("Logout");
		logoutButton.setImmediate(true);
		logoutButton.setWidth("-1px");
		logoutButton.setHeight("20px");
		mainLayout.addComponent(logoutButton, "top:0.0px;left:0.0px;");
		
		return mainLayout;
	}

	@AutoGenerated
	private TabSheet buildMailingListTab() {
		// common part: create layout
		mailingListTab = new TabSheet();
		mailingListTab.setStyleName("background");
		mailingListTab.setCaption("Mailing Lists");
		mailingListTab.setImmediate(true);
		mailingListTab.setWidth("50.0%");
		mailingListTab.setHeight("100.0%");
		
		// mailingListContainer
		mailingListContainer = buildMailingListContainer();
		mailingListTab.addTab(mailingListContainer, "", null);
		
		// twitterLayout
		twitterLayout = buildTwitterLayout();
		mailingListTab.addTab(twitterLayout, "", null);
		
		// facebookContainer
		facebookContainer = buildFacebookContainer();
		mailingListTab.addTab(facebookContainer, "", null);
		
		// sendMessages
		sendMessages = buildSendMessages();
		mailingListTab.addTab(sendMessages, "Messages", null);
		
		// analyticsDashBoard
		analyticsDashBoard = new AnalyticsDashBoard();
		analyticsDashBoard.setImmediate(false);
		analyticsDashBoard.setWidth("-1px");
		analyticsDashBoard.setHeight("-1px");
		mailingListTab.addTab(analyticsDashBoard, "Analytics", null);
		
		return mailingListTab;
	}

	@AutoGenerated
	private VerticalLayout buildMailingListContainer() {
		// common part: create layout
		mailingListContainer = new VerticalLayout();
		mailingListContainer.setStyleName("background");
		mailingListContainer.setImmediate(false);
		mailingListContainer.setWidth("100.0%");
		mailingListContainer.setHeight("100.0%");
		mailingListContainer.setMargin(false);
		
		// manageMailingAccount_2
		manageMailingAccount_2 = new ManageMailingAccount();
		manageMailingAccount_2.setImmediate(false);
		manageMailingAccount_2.setWidth("-1px");
		manageMailingAccount_2.setHeight("-1px");
		mailingListContainer.addComponent(manageMailingAccount_2);
		
		return mailingListContainer;
	}

	@AutoGenerated
	private VerticalLayout buildTwitterLayout() {
		// common part: create layout
		twitterLayout = new VerticalLayout();
		twitterLayout.setStyleName("background");
		twitterLayout.setImmediate(false);
		twitterLayout.setWidth("100.0%");
		twitterLayout.setHeight("368px");
		twitterLayout.setMargin(false);
		
		// horizontalSplitPanel_3
		horizontalSplitPanel_3 = buildHorizontalSplitPanel_3();
		twitterLayout.addComponent(horizontalSplitPanel_3);
		
		return twitterLayout;
	}

	@AutoGenerated
	private HorizontalSplitPanel buildHorizontalSplitPanel_3() {
		// common part: create layout
		horizontalSplitPanel_3 = new HorizontalSplitPanel();
		horizontalSplitPanel_3.setImmediate(false);
		horizontalSplitPanel_3.setWidth("400px");
		horizontalSplitPanel_3.setHeight("308px");
		horizontalSplitPanel_3.setMargin(false);
		
		// verticalLayout_3
		verticalLayout_3 = buildVerticalLayout_3();
		horizontalSplitPanel_3.addComponent(verticalLayout_3);
		
		// twitterPanel
		twitterPanel = buildTwitterPanel();
		horizontalSplitPanel_3.addComponent(twitterPanel);
		
		return horizontalSplitPanel_3;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_3() {
		// common part: create layout
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setWidth("-1px");
		verticalLayout_3.setHeight("-1px");
		verticalLayout_3.setMargin(false);
		
		// openTwitterButton
		openTwitterButton = new Button();
		openTwitterButton.setStyleName("decorated");
		openTwitterButton.setCaption("Authorize Twitter");
		openTwitterButton.setImmediate(true);
		openTwitterButton.setWidth("-1px");
		openTwitterButton.setHeight("-1px");
		verticalLayout_3.addComponent(openTwitterButton);
		
		// twitterSelectList
		twitterSelectList = new ListSelect();
		twitterSelectList.setImmediate(false);
		twitterSelectList.setWidth("-1px");
		twitterSelectList.setHeight("-1px");
		verticalLayout_3.addComponent(twitterSelectList);
		
		// deleteTwitterButton
		deleteTwitterButton = new Button();
		deleteTwitterButton.setStyleName("decorated");
		deleteTwitterButton.setCaption("Delete Account");
		deleteTwitterButton.setImmediate(true);
		deleteTwitterButton.setWidth("-1px");
		deleteTwitterButton.setHeight("-1px");
		verticalLayout_3.addComponent(deleteTwitterButton);
		
		return verticalLayout_3;
	}

	@AutoGenerated
	private VerticalSplitPanel buildTwitterPanel() {
		// common part: create layout
		twitterPanel = new VerticalSplitPanel();
		twitterPanel.setImmediate(false);
		twitterPanel.setWidth("200px");
		twitterPanel.setHeight("288px");
		twitterPanel.setMargin(false);
		
		// twitterPanelTop
		twitterPanelTop = new VerticalLayout();
		twitterPanelTop.setCaption("Enabled Twitter Accounts");
		twitterPanelTop.setImmediate(false);
		twitterPanelTop.setWidth("-1px");
		twitterPanelTop.setHeight("-1px");
		twitterPanelTop.setMargin(false);
		twitterPanel.addComponent(twitterPanelTop);
		
		// twitterPanelBottom
		twitterPanelBottom = buildTwitterPanelBottom();
		twitterPanel.addComponent(twitterPanelBottom);
		
		return twitterPanel;
	}

	@AutoGenerated
	private VerticalLayout buildTwitterPanelBottom() {
		// common part: create layout
		twitterPanelBottom = new VerticalLayout();
		twitterPanelBottom.setImmediate(false);
		twitterPanelBottom.setWidth("-1px");
		twitterPanelBottom.setHeight("-1px");
		twitterPanelBottom.setMargin(false);
		
		// disabledTwitterAccountsLabel
		disabledTwitterAccountsLabel = new Label();
		disabledTwitterAccountsLabel.setImmediate(false);
		disabledTwitterAccountsLabel.setWidth("-1px");
		disabledTwitterAccountsLabel.setHeight("-1px");
		disabledTwitterAccountsLabel.setValue("Disabled Twitter Accounts");
		twitterPanelBottom.addComponent(disabledTwitterAccountsLabel);
		
		return twitterPanelBottom;
	}

	@AutoGenerated
	private VerticalLayout buildFacebookContainer() {
		// common part: create layout
		facebookContainer = new VerticalLayout();
		facebookContainer.setStyleName("background");
		facebookContainer.setImmediate(false);
		facebookContainer.setWidth("100.0%");
		facebookContainer.setHeight("100.0%");
		facebookContainer.setMargin(false);
		
		// horizontalSplitPanel_2
		horizontalSplitPanel_2 = buildHorizontalSplitPanel_2();
		facebookContainer.addComponent(horizontalSplitPanel_2);
		
		return facebookContainer;
	}

	@AutoGenerated
	private HorizontalSplitPanel buildHorizontalSplitPanel_2() {
		// common part: create layout
		horizontalSplitPanel_2 = new HorizontalSplitPanel();
		horizontalSplitPanel_2.setImmediate(false);
		horizontalSplitPanel_2.setWidth("400px");
		horizontalSplitPanel_2.setHeight("348px");
		horizontalSplitPanel_2.setMargin(false);
		
		// verticalLayout_5
		verticalLayout_5 = buildVerticalLayout_5();
		horizontalSplitPanel_2.addComponent(verticalLayout_5);
		
		// facebookPanel
		facebookPanel = buildFacebookPanel();
		horizontalSplitPanel_2.addComponent(facebookPanel);
		
		return horizontalSplitPanel_2;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_5() {
		// common part: create layout
		verticalLayout_5 = new VerticalLayout();
		verticalLayout_5.setImmediate(false);
		verticalLayout_5.setWidth("225px");
		verticalLayout_5.setHeight("368px");
		verticalLayout_5.setMargin(false);
		
		// importFacebookButton
		importFacebookButton = new Button();
		importFacebookButton.setStyleName("decorated");
		importFacebookButton.setCaption("Import Facebook Pages");
		importFacebookButton.setImmediate(true);
		importFacebookButton
				.setDescription("Click this to import fan pages you manage.");
		importFacebookButton.setWidth("-1px");
		importFacebookButton.setHeight("-1px");
		verticalLayout_5.addComponent(importFacebookButton);
		
		// openFacebook
		openFacebook = new Button();
		openFacebook.setStyleName("decorated");
		openFacebook.setCaption("Allow Account");
		openFacebook.setImmediate(true);
		openFacebook
				.setDescription("Click this to allow import a new facebook account");
		openFacebook.setWidth("159px");
		openFacebook.setHeight("-1px");
		verticalLayout_5.addComponent(openFacebook);
		
		// facebookAccountSelect
		facebookAccountSelect = new ListSelect();
		facebookAccountSelect.setImmediate(false);
		facebookAccountSelect.setWidth("-1px");
		facebookAccountSelect.setHeight("-1px");
		verticalLayout_5.addComponent(facebookAccountSelect);
		
		// deleteFacebookButton
		deleteFacebookButton = new Button();
		deleteFacebookButton.setStyleName("decorated");
		deleteFacebookButton.setCaption("Delete Account");
		deleteFacebookButton.setImmediate(true);
		deleteFacebookButton.setWidth("-1px");
		deleteFacebookButton.setHeight("-1px");
		verticalLayout_5.addComponent(deleteFacebookButton);
		
		return verticalLayout_5;
	}

	@AutoGenerated
	private VerticalSplitPanel buildFacebookPanel() {
		// common part: create layout
		facebookPanel = new VerticalSplitPanel();
		facebookPanel.setImmediate(false);
		facebookPanel.setWidth("196px");
		facebookPanel.setHeight("338px");
		facebookPanel.setMargin(false);
		
		// facebookPanelTop
		facebookPanelTop = buildFacebookPanelTop();
		facebookPanel.addComponent(facebookPanelTop);
		
		// facebookPanelBottom
		facebookPanelBottom = buildFacebookPanelBottom();
		facebookPanel.addComponent(facebookPanelBottom);
		
		return facebookPanel;
	}

	@AutoGenerated
	private VerticalLayout buildFacebookPanelTop() {
		// common part: create layout
		facebookPanelTop = new VerticalLayout();
		facebookPanelTop.setImmediate(false);
		facebookPanelTop.setWidth("-1px");
		facebookPanelTop.setHeight("-1px");
		facebookPanelTop.setMargin(false);
		
		// activeFacebookLabel
		activeFacebookLabel = new Label();
		activeFacebookLabel.setImmediate(false);
		activeFacebookLabel.setWidth("-1px");
		activeFacebookLabel.setHeight("-1px");
		activeFacebookLabel.setValue("Active Facebook Accounts");
		facebookPanelTop.addComponent(activeFacebookLabel);
		
		return facebookPanelTop;
	}

	@AutoGenerated
	private VerticalLayout buildFacebookPanelBottom() {
		// common part: create layout
		facebookPanelBottom = new VerticalLayout();
		facebookPanelBottom.setImmediate(false);
		facebookPanelBottom.setWidth("-1px");
		facebookPanelBottom.setHeight("-1px");
		facebookPanelBottom.setMargin(false);
		
		// inactiveFacebookLabel
		inactiveFacebookLabel = new Label();
		inactiveFacebookLabel.setImmediate(false);
		inactiveFacebookLabel.setWidth("-1px");
		inactiveFacebookLabel.setHeight("-1px");
		inactiveFacebookLabel.setValue("Inactive Facebook Accounts");
		facebookPanelBottom.addComponent(inactiveFacebookLabel);
		
		return facebookPanelBottom;
	}

	@AutoGenerated
	private VerticalLayout buildSendMessages() {
		// common part: create layout
		sendMessages = new VerticalLayout();
		sendMessages.setStyleName("background");
		sendMessages.setImmediate(false);
		sendMessages.setWidth("100.0%");
		sendMessages.setHeight("100.0%");
		sendMessages.setMargin(false);
		
		// verticalSplitPanel_1
		verticalSplitPanel_1 = buildVerticalSplitPanel_1();
		sendMessages.addComponent(verticalSplitPanel_1);
		
		return sendMessages;
	}

	@AutoGenerated
	private VerticalSplitPanel buildVerticalSplitPanel_1() {
		// common part: create layout
		verticalSplitPanel_1 = new VerticalSplitPanel();
		verticalSplitPanel_1.setImmediate(false);
		verticalSplitPanel_1.setWidth("709px");
		verticalSplitPanel_1.setHeight("568px");
		verticalSplitPanel_1.setMargin(false);
		
		// horizontalSplitPanel_1
		horizontalSplitPanel_1 = buildHorizontalSplitPanel_1();
		verticalSplitPanel_1.addComponent(horizontalSplitPanel_1);
		
		// messageManagementTab
		messageManagementTab = buildMessageManagementTab();
		verticalSplitPanel_1.addComponent(messageManagementTab);
		
		return verticalSplitPanel_1;
	}

	@AutoGenerated
	private HorizontalSplitPanel buildHorizontalSplitPanel_1() {
		// common part: create layout
		horizontalSplitPanel_1 = new HorizontalSplitPanel();
		horizontalSplitPanel_1.setImmediate(false);
		horizontalSplitPanel_1.setWidth("699px");
		horizontalSplitPanel_1.setHeight("250px");
		horizontalSplitPanel_1.setMargin(false);
		
		// messageSendingColSelect
		messageSendingColSelect = new TwinColSelect();
		messageSendingColSelect.setImmediate(false);
		messageSendingColSelect.setWidth("356px");
		messageSendingColSelect.setHeight("-1px");
		horizontalSplitPanel_1.addComponent(messageSendingColSelect);
		
		// timedMessagePanel
		timedMessagePanel = buildTimedMessagePanel();
		horizontalSplitPanel_1.addComponent(timedMessagePanel);
		
		return horizontalSplitPanel_1;
	}

	@AutoGenerated
	private VerticalLayout buildTimedMessagePanel() {
		// common part: create layout
		timedMessagePanel = new VerticalLayout();
		timedMessagePanel.setCaption("Timed Message");
		timedMessagePanel.setImmediate(false);
		timedMessagePanel.setWidth("-1px");
		timedMessagePanel.setHeight("280px");
		timedMessagePanel.setMargin(false);
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		timedMessagePanel.addComponent(verticalLayout_2);
		
		return timedMessagePanel;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("-1px");
		verticalLayout_2.setHeight("250px");
		verticalLayout_2.setMargin(false);
		
		// timedMessage
		timedMessage = new Label();
		timedMessage.setImmediate(false);
		timedMessage.setWidth("-1px");
		timedMessage.setHeight("-1px");
		timedMessage.setValue("Schedule Message:");
		verticalLayout_2.addComponent(timedMessage);
		
		// inlineDateField_1
		inlineDateField_1 = new InlineDateField();
		inlineDateField_1.setImmediate(false);
		inlineDateField_1.setWidth("-1px");
		inlineDateField_1.setHeight("-1px");
		inlineDateField_1.setInvalidAllowed(false);
		verticalLayout_2.addComponent(inlineDateField_1);
		
		// schedulePost
		schedulePost = new Button();
		schedulePost.setStyleName("decorated");
		schedulePost.setCaption("Schedule Message");
		schedulePost.setImmediate(true);
		schedulePost.setWidth("-1px");
		schedulePost.setHeight("-1px");
		verticalLayout_2.addComponent(schedulePost);
		
		return verticalLayout_2;
	}

	@AutoGenerated
	private HorizontalLayout buildMessageManagementTab() {
		// common part: create layout
		messageManagementTab = new HorizontalLayout();
		messageManagementTab.setImmediate(false);
		messageManagementTab.setWidth("-1px");
		messageManagementTab.setHeight("-1px");
		messageManagementTab.setMargin(false);
		
		// sentMessagesSelect
		sentMessagesSelect = new ListSelect();
		sentMessagesSelect.setCaption("Current timed messages:");
		sentMessagesSelect.setImmediate(false);
		sentMessagesSelect.setWidth("100px");
		sentMessagesSelect.setHeight("-1px");
		messageManagementTab.addComponent(sentMessagesSelect);
		
		// editTimedMessageButton
		editTimedMessageButton = new Button();
		editTimedMessageButton.setStyleName("decorated");
		editTimedMessageButton.setCaption("Edit");
		editTimedMessageButton.setImmediate(true);
		editTimedMessageButton.setWidth("-1px");
		editTimedMessageButton.setHeight("-1px");
		messageManagementTab.addComponent(editTimedMessageButton);
		
		// deleteTimedMessageButton
		deleteTimedMessageButton = new Button();
		deleteTimedMessageButton.setStyleName("decorated");
		deleteTimedMessageButton.setCaption("Delete");
		deleteTimedMessageButton.setImmediate(true);
		deleteTimedMessageButton.setWidth("-1px");
		deleteTimedMessageButton.setHeight("-1px");
		messageManagementTab.addComponent(deleteTimedMessageButton);
		
		// draftListSelect
		draftListSelect = new ListSelect();
		draftListSelect.setCaption("Saved Drafts:");
		draftListSelect.setImmediate(false);
		draftListSelect.setWidth("100px");
		draftListSelect.setHeight("-1px");
		messageManagementTab.addComponent(draftListSelect);
		
		// editDraftButton
		editDraftButton = new Button();
		editDraftButton.setStyleName("decorated");
		editDraftButton.setCaption("Edit");
		editDraftButton.setImmediate(true);
		editDraftButton.setWidth("-1px");
		editDraftButton.setHeight("-1px");
		messageManagementTab.addComponent(editDraftButton);
		
		// deleteDraftButton
		deleteDraftButton = new Button();
		deleteDraftButton.setStyleName("decorated");
		deleteDraftButton.setCaption("Delete");
		deleteDraftButton.setImmediate(true);
		deleteDraftButton.setWidth("-1px");
		deleteDraftButton.setHeight("-1px");
		messageManagementTab.addComponent(deleteDraftButton);
		
		return messageManagementTab;
	}

	@AutoGenerated
	private TabSheet buildRichEmail() {
		// common part: create layout
		richEmail = new TabSheet();
		richEmail.setStyleName("background");
		richEmail.setImmediate(true);
		richEmail.setWidth("50.0%");
		richEmail.setHeight("100.0%");
		
		// richEmailLayout
		richEmailLayout = buildRichEmailLayout();
		richEmail.addTab(richEmailLayout, "Rich Email", null);
		
		// simpleSendContainer
		simpleSendContainer = buildSimpleSendContainer();
		richEmail.addTab(simpleSendContainer, "Publish to All", null);
		
		return richEmail;
	}

	@AutoGenerated
	private VerticalLayout buildRichEmailLayout() {
		// common part: create layout
		richEmailLayout = new VerticalLayout();
		richEmailLayout.setStyleName("background");
		richEmailLayout.setImmediate(false);
		richEmailLayout.setWidth("100.0%");
		richEmailLayout.setHeight("100.0%");
		richEmailLayout.setMargin(false);
		
		// richEmailWrapper
		richEmailWrapper = buildRichEmailWrapper();
		richEmailLayout.addComponent(richEmailWrapper);
		
		return richEmailLayout;
	}

	@AutoGenerated
	private VerticalLayout buildRichEmailWrapper() {
		// common part: create layout
		richEmailWrapper = new VerticalLayout();
		richEmailWrapper.setImmediate(false);
		richEmailWrapper.setWidth("100.0%");
		richEmailWrapper.setHeight("588px");
		richEmailWrapper.setMargin(false);
		
		// subjectWrapperLayout
		subjectWrapperLayout = buildSubjectWrapperLayout();
		richEmailWrapper.addComponent(subjectWrapperLayout);
		
		// cKEditorTextField_1
		cKEditorTextField_1 = new CKEditorTextField();
		cKEditorTextField_1.setImmediate(false);
		cKEditorTextField_1.setWidth("538px");
		cKEditorTextField_1.setHeight("400px");
		richEmailWrapper.addComponent(cKEditorTextField_1);
		
		// bottomLayout
		bottomLayout = buildBottomLayout();
		richEmailWrapper.addComponent(bottomLayout);
		
		return richEmailWrapper;
	}

	@AutoGenerated
	private HorizontalLayout buildSubjectWrapperLayout() {
		// common part: create layout
		subjectWrapperLayout = new HorizontalLayout();
		subjectWrapperLayout.setImmediate(false);
		subjectWrapperLayout.setWidth("100.0%");
		subjectWrapperLayout.setHeight("-1px");
		subjectWrapperLayout.setMargin(false);
		
		// subjectTextField
		subjectTextField = new TextField();
		subjectTextField.setCaption("Subject:");
		subjectTextField.setImmediate(false);
		subjectTextField.setWidth("238px");
		subjectTextField.setHeight("-1px");
		subjectTextField.setSecret(false);
		subjectWrapperLayout.addComponent(subjectTextField);
		
		return subjectWrapperLayout;
	}

	@AutoGenerated
	private VerticalLayout buildBottomLayout() {
		// common part: create layout
		bottomLayout = new VerticalLayout();
		bottomLayout.setImmediate(false);
		bottomLayout.setWidth("500px");
		bottomLayout.setHeight("500px");
		bottomLayout.setMargin(false);
		
		// addAttachment
		addAttachment = new Upload();
		addAttachment.setCaption("Add attchment");
		addAttachment.setImmediate(false);
		addAttachment.setWidth("100.0%");
		addAttachment.setHeight("105px");
		bottomLayout.addComponent(addAttachment);
		
		// richFileAttachmentSelect
		richFileAttachmentSelect = new ListSelect();
		richFileAttachmentSelect.setCaption("Current Attachments");
		richFileAttachmentSelect.setImmediate(false);
		richFileAttachmentSelect.setWidth("221px");
		richFileAttachmentSelect.setHeight("100px");
		bottomLayout.addComponent(richFileAttachmentSelect);
		
		// sendRichWrapper
		sendRichWrapper = buildSendRichWrapper();
		bottomLayout.addComponent(sendRichWrapper);
		
		return bottomLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildSendRichWrapper() {
		// common part: create layout
		sendRichWrapper = new HorizontalLayout();
		sendRichWrapper.setImmediate(false);
		sendRichWrapper.setWidth("100.0%");
		sendRichWrapper.setHeight("100px");
		sendRichWrapper.setMargin(false);
		
		// sendRichEmail
		sendRichEmail = new Button();
		sendRichEmail.setCaption("Send");
		sendRichEmail.setImmediate(true);
		sendRichEmail.setWidth("118px");
		sendRichEmail.setHeight("25px");
		sendRichWrapper.addComponent(sendRichEmail);
		
		// saveRichTabButton
		saveRichTabButton = new Button();
		saveRichTabButton.setCaption("Save Draft");
		saveRichTabButton.setImmediate(true);
		saveRichTabButton.setWidth("75px");
		saveRichTabButton.setHeight("25px");
		sendRichWrapper.addComponent(saveRichTabButton);
		
		return sendRichWrapper;
	}

	@AutoGenerated
	private VerticalLayout buildSimpleSendContainer() {
		// common part: create layout
		simpleSendContainer = new VerticalLayout();
		simpleSendContainer.setStyleName("background");
		simpleSendContainer.setImmediate(false);
		simpleSendContainer.setWidth("100.0%");
		simpleSendContainer.setHeight("800px");
		simpleSendContainer.setMargin(false);
		
		// verticalLayout_10
		verticalLayout_10 = buildVerticalLayout_10();
		simpleSendContainer.addComponent(verticalLayout_10);
		
		return simpleSendContainer;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_10() {
		// common part: create layout
		verticalLayout_10 = new VerticalLayout();
		verticalLayout_10.setImmediate(false);
		verticalLayout_10.setWidth("500px");
		verticalLayout_10.setHeight("-1px");
		verticalLayout_10.setMargin(false);
		
		// simpleSendSubjectText
		simpleSendSubjectText = new TextField();
		simpleSendSubjectText.setCaption("Subject:");
		simpleSendSubjectText.setImmediate(false);
		simpleSendSubjectText.setWidth("310px");
		simpleSendSubjectText.setHeight("-1px");
		simpleSendSubjectText.setSecret(false);
		verticalLayout_10.addComponent(simpleSendSubjectText);
		
		// verticalLayout_7
		verticalLayout_7 = buildVerticalLayout_7();
		verticalLayout_10.addComponent(verticalLayout_7);
		
		return verticalLayout_10;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_7() {
		// common part: create layout
		verticalLayout_7 = new VerticalLayout();
		verticalLayout_7.setImmediate(false);
		verticalLayout_7.setWidth("100.0%");
		verticalLayout_7.setHeight("-1px");
		verticalLayout_7.setMargin(false);
		
		// simpleAttachment
		simpleAttachment = new Upload();
		simpleAttachment.setCaption("Upload file");
		simpleAttachment.setImmediate(false);
		simpleAttachment.setWidth("400px");
		simpleAttachment.setHeight("42px");
		verticalLayout_7.addComponent(simpleAttachment);
		
		// simpleAttachmentSelect
		simpleAttachmentSelect = new ListSelect();
		simpleAttachmentSelect.setCaption("Current Attachments");
		simpleAttachmentSelect.setImmediate(false);
		simpleAttachmentSelect.setWidth("100px");
		simpleAttachmentSelect.setHeight("-1px");
		verticalLayout_7.addComponent(simpleAttachmentSelect);
		
		// verticalLayout_11
		verticalLayout_11 = buildVerticalLayout_11();
		verticalLayout_7.addComponent(verticalLayout_11);
		
		return verticalLayout_7;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_11() {
		// common part: create layout
		verticalLayout_11 = new VerticalLayout();
		verticalLayout_11.setImmediate(false);
		verticalLayout_11.setWidth("-1px");
		verticalLayout_11.setHeight("-1px");
		verticalLayout_11.setMargin(false);
		
		// horizontalLayout_3
		horizontalLayout_3 = buildHorizontalLayout_3();
		verticalLayout_11.addComponent(horizontalLayout_3);
		
		// simpleSendTextArea
		simpleSendTextArea = new TextArea();
		simpleSendTextArea.setCaption("Send a simple message");
		simpleSendTextArea.setImmediate(false);
		simpleSendTextArea.setWidth("658px");
		simpleSendTextArea.setHeight("180px");
		simpleSendTextArea.setMaxLength(140);
		verticalLayout_11.addComponent(simpleSendTextArea);
		
		return verticalLayout_11;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_3() {
		// common part: create layout
		horizontalLayout_3 = new HorizontalLayout();
		horizontalLayout_3.setImmediate(false);
		horizontalLayout_3.setWidth("-1px");
		horizontalLayout_3.setHeight("-1px");
		horizontalLayout_3.setMargin(false);
		
		// saveSimpleDraftButton
		saveSimpleDraftButton = new Button();
		saveSimpleDraftButton.setCaption("Save Draft");
		saveSimpleDraftButton.setImmediate(true);
		saveSimpleDraftButton.setWidth("-1px");
		saveSimpleDraftButton.setHeight("-1px");
		horizontalLayout_3.addComponent(saveSimpleDraftButton);
		
		// simpleSendButton
		simpleSendButton = new Button();
		simpleSendButton.setCaption("Send Message");
		simpleSendButton.setImmediate(true);
		simpleSendButton.setWidth("-1px");
		simpleSendButton.setHeight("-1px");
		horizontalLayout_3.addComponent(simpleSendButton);
		
		return horizontalLayout_3;
	}

}
