package com.ccc.ui.widgets;
import org.springframework.context.annotation.DependsOn;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Label;
import com.vaadin.ui.LoginForm;
import com.vaadin.ui.LoginForm.LoginListener;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

@Component("loginComponent")
@Scope("session")
@DependsOn("appSyc")
public class LoginComponent extends CustomComponent  {

	@AutoGenerated
	private GridLayout mainLayout;
	@AutoGenerated
	private TabSheet logintab;
	@AutoGenerated
	private HorizontalSplitPanel forgotTab;
	@AutoGenerated
	private VerticalLayout forgotUserNameDiv;
	@AutoGenerated
	private Button sendEmail;
	@AutoGenerated
	private TextField forgotUserName;
	@AutoGenerated
	private Label forgotUserNameLabel;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private Button sendReset;
	@AutoGenerated
	private TextField userName;
	@AutoGenerated
	private Label forgotPasswordLabel2;
	@AutoGenerated
	private AbsoluteLayout registerTab;
	@AutoGenerated
	private Button register;
	@AutoGenerated
	private HorizontalLayout companyDiv;
	@AutoGenerated
	private TextField company;
	@AutoGenerated
	private Label companyLabel;
	@AutoGenerated
	private HorizontalLayout confirmDiv;
	@AutoGenerated
	private PasswordField passwordConfirm;
	@AutoGenerated
	private Label confirmLabel;
	@AutoGenerated
	private HorizontalLayout lastNameDiv;
	@AutoGenerated
	private TextField lastName;
	@AutoGenerated
	private Label lastNameLabel;
	@AutoGenerated
	private HorizontalLayout firstNameDiv;
	@AutoGenerated
	private TextField firstName;
	@AutoGenerated
	private Label firstNameLabel;
	@AutoGenerated
	private HorizontalLayout passwordDiv;
	@AutoGenerated
	private PasswordField passwordField;
	@AutoGenerated
	private Label passwordLabel;
	@AutoGenerated
	private HorizontalLayout emailDiv;
	@AutoGenerated
	private TextField email;
	@AutoGenerated
	private Label emailLabel;
	@AutoGenerated
	private HorizontalLayout loginTab;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private LoginForm loginForm_2;
	@AutoGenerated
	private Label loginLabel;

	/*- VaadinEditorProperties={"grid":"RegularGrid,100","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":true,"snappingDistance":8} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,100","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":true,"snappingDistance":8} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,100","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":true,"snappingDistance":8} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,100","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":true,"snappingDistance":8} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,100","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":true,"snappingDistance":8} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,100","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":true,"snappingDistance":8} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,100","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":true,"snappingDistance":8} */

	public Button getSendEmail() {
		return sendEmail;
	}

	public void setSendEmail(Button sendEmail) {
		this.sendEmail = sendEmail;
	}

	public TextField getForgotUserName() {
		return forgotUserName;
	}

	public void setForgotUserName(TextField forgotUserName) {
		this.forgotUserName = forgotUserName;
	}

	public Button getSendReset() {
		return sendReset;
	}

	public void setSendReset(Button sendReset) {
		this.sendReset = sendReset;
	}

	public TextField getUserName() {
		return userName;
	}

	public void setUserName(TextField userName) {
		this.userName = userName;
	}

	public Button getRegister() {
		return register;
	}

	public void setRegister(Button register) {
		this.register = register;
	}

	public TextField getCompany() {
		return company;
	}

	public void setCompany(TextField company) {
		this.company = company;
	}

	public PasswordField getPasswordConfirm() {
		return passwordConfirm;
	}

	public void setPasswordConfirm(PasswordField passwordConfirm) {
		this.passwordConfirm = passwordConfirm;
	}

	public TextField getLastName() {
		return lastName;
	}

	public void setLastName(TextField lastName) {
		this.lastName = lastName;
	}

	public TextField getFirstName() {
		return firstName;
	}

	public void setFirstName(TextField firstName) {
		this.firstName = firstName;
	}

	public PasswordField getPasswordField() {
		return passwordField;
	}

	public void setPasswordField(PasswordField passwordField) {
		this.passwordField = passwordField;
	}

	public TextField getEmail() {
		return email;
	}

	public void setEmail(TextField email) {
		this.email = email;
	}

	public TabSheet getLoginTab() {
		return logintab;
	}

	/*- VaadinEditorProperties={"grid":"RegularGrid,100","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":true,"snappingDistance":8} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,100","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":true,"snappingDistance":8} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,100","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":true,"snappingDistance":8} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,100","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":true,"snappingDistance":8} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,100","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":true,"snappingDistance":8} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,100","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":true,"snappingDistance":8} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,100","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":true,"snappingDistance":8} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,100","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":true,"snappingDistance":8} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,100","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":true,"snappingDistance":8} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,100","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":true,"snappingDistance":8} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,100","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":true,"snappingDistance":8} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */



	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public LoginComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		mainLayout.setVisible(true);
		mainLayout.setEnabled(true);
		this.setSizeUndefined();	
		
	}
	
	public void addLoginListener(LoginListener listener) {
		this.loginForm_2.addListener(listener);
	}
	
	
	
	

	@AutoGenerated
	private GridLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new GridLayout();
		mainLayout.setStyleName("background");
		mainLayout.setImmediate(false);
		mainLayout.setWidth("480px");
		mainLayout.setHeight("450px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("480px");
		setHeight("450px");
		
		// logintab
		logintab = buildLogintab();
		mainLayout.addComponent(logintab, 0, 0);
		
		return mainLayout;
	}

	@AutoGenerated
	private TabSheet buildLogintab() {
		// common part: create layout
		logintab = new TabSheet();
		logintab.setStyleName("background");
		logintab.setImmediate(true);
		logintab.setWidth("479px");
		logintab.setHeight("450px");
		
		// loginTab
		loginTab = buildLoginTab();
		logintab.addTab(loginTab, "Login", null);
		
		// registerTab
		registerTab = buildRegisterTab();
		logintab.addTab(registerTab, "Register", null);
		
		// forgotTab
		forgotTab = buildForgotTab();
		logintab.addTab(forgotTab, "Forgot Something?", null);
		
		return logintab;
	}

	@AutoGenerated
	private HorizontalLayout buildLoginTab() {
		// common part: create layout
		loginTab = new HorizontalLayout();
		loginTab.setImmediate(false);
		loginTab.setWidth("500px");
		loginTab.setHeight("100.0%");
		loginTab.setMargin(false);
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		loginTab.addComponent(verticalLayout_2);
		loginTab.setComponentAlignment(verticalLayout_2, new Alignment(48));
		
		return loginTab;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("259px");
		verticalLayout_2.setHeight("-1px");
		verticalLayout_2.setMargin(false);
		
		// loginLabel
		loginLabel = new Label();
		loginLabel.setImmediate(false);
		loginLabel.setWidth("200px");
		loginLabel.setHeight("-1px");
		loginLabel.setValue("Welcome to AppSyc!");
		verticalLayout_2.addComponent(loginLabel);
		verticalLayout_2.setComponentAlignment(loginLabel, new Alignment(20));
		
		// loginForm_2
		loginForm_2 = new LoginForm();
		loginForm_2.setStyleName("v-loginform");
		loginForm_2.setImmediate(false);
		loginForm_2.setWidth("90.72%");
		loginForm_2.setHeight("-1px");
		verticalLayout_2.addComponent(loginForm_2);
		verticalLayout_2.setComponentAlignment(loginForm_2, new Alignment(48));
		
		return verticalLayout_2;
	}

	@AutoGenerated
	private AbsoluteLayout buildRegisterTab() {
		// common part: create layout
		registerTab = new AbsoluteLayout();
		registerTab.setImmediate(false);
		registerTab.setWidth("100.0%");
		registerTab.setHeight("248px");
		registerTab.setMargin(false);
		
		// emailDiv
		emailDiv = buildEmailDiv();
		registerTab.addComponent(emailDiv,
				"top:0.0px;bottom:215.0px;left:0.0px;");
		
		// passwordDiv
		passwordDiv = buildPasswordDiv();
		registerTab.addComponent(passwordDiv, "top:34.0px;left:0.0px;");
		
		// firstNameDiv
		firstNameDiv = buildFirstNameDiv();
		registerTab.addComponent(firstNameDiv,
				"top:108.0px;bottom:107.0px;left:0.0px;");
		
		// lastNameDiv
		lastNameDiv = buildLastNameDiv();
		registerTab.addComponent(lastNameDiv, "top:147.0px;left:0.0px;");
		
		// confirmDiv
		confirmDiv = buildConfirmDiv();
		registerTab.addComponent(confirmDiv,
				"top:72.0px;right:186.0px;bottom:145.0px;left:0.0px;");
		
		// companyDiv
		companyDiv = buildCompanyDiv();
		registerTab.addComponent(companyDiv, "top:200.0px;left:0.0px;");
		
		// register
		register = new Button();
		register.setStyleName("decorated");
		register.setCaption("Register");
		register.setImmediate(true);
		register.setWidth("-1px");
		register.setHeight("-1px");
		registerTab.addComponent(register, "top:228.0px;left:220.0px;");
		
		return registerTab;
	}

	@AutoGenerated
	private HorizontalLayout buildEmailDiv() {
		// common part: create layout
		emailDiv = new HorizontalLayout();
		emailDiv.setImmediate(false);
		emailDiv.setWidth("291px");
		emailDiv.setHeight("100.0%");
		emailDiv.setMargin(false);
		
		// emailLabel
		emailLabel = new Label();
		emailLabel.setStyleName("emailLabel");
		emailLabel.setImmediate(false);
		emailLabel.setWidth("63px");
		emailLabel.setHeight("15px");
		emailLabel.setValue("Email:");
		emailDiv.addComponent(emailLabel);
		emailDiv.setComponentAlignment(emailLabel, new Alignment(9));
		
		// email
		email = new TextField();
		email.setCaption("Email Required");
		email.setImmediate(false);
		email.setWidth("197px");
		email.setHeight("18px");
		email.setRequired(true);
		email.setSecret(false);
		emailDiv.addComponent(email);
		emailDiv.setComponentAlignment(email, new Alignment(34));
		
		return emailDiv;
	}

	@AutoGenerated
	private HorizontalLayout buildPasswordDiv() {
		// common part: create layout
		passwordDiv = new HorizontalLayout();
		passwordDiv.setImmediate(false);
		passwordDiv.setDescription("Your password");
		passwordDiv.setWidth("291px");
		passwordDiv.setHeight("34px");
		passwordDiv.setMargin(false);
		
		// passwordLabel
		passwordLabel = new Label();
		passwordLabel.setImmediate(false);
		passwordLabel.setWidth("80px");
		passwordLabel.setHeight("20px");
		passwordLabel.setValue("Password:");
		passwordDiv.addComponent(passwordLabel);
		passwordDiv.setComponentAlignment(passwordLabel, new Alignment(9));
		
		// passwordField
		passwordField = new PasswordField();
		passwordField.setCaption("Need Password");
		passwordField.setImmediate(false);
		passwordField.setWidth("197px");
		passwordField.setHeight("20px");
		passwordField.setRequired(true);
		passwordDiv.addComponent(passwordField);
		passwordDiv.setComponentAlignment(passwordField, new Alignment(34));
		
		return passwordDiv;
	}

	@AutoGenerated
	private HorizontalLayout buildFirstNameDiv() {
		// common part: create layout
		firstNameDiv = new HorizontalLayout();
		firstNameDiv.setImmediate(false);
		firstNameDiv.setWidth("291px");
		firstNameDiv.setHeight("100.0%");
		firstNameDiv.setMargin(false);
		
		// firstNameLabel
		firstNameLabel = new Label();
		firstNameLabel.setStyleName("firstNameLabel");
		firstNameLabel.setImmediate(false);
		firstNameLabel.setWidth("69px");
		firstNameLabel.setHeight("60.0%");
		firstNameLabel.setValue("First Name:");
		firstNameDiv.addComponent(firstNameLabel);
		firstNameDiv.setComponentAlignment(firstNameLabel, new Alignment(9));
		
		// firstName
		firstName = new TextField();
		firstName.setStyleName("firstName");
		firstName.setCaption("First Name Required:");
		firstName.setImmediate(false);
		firstName.setWidth("202px");
		firstName.setHeight("18px");
		firstName.setRequired(true);
		firstName.setSecret(false);
		firstNameDiv.addComponent(firstName);
		firstNameDiv.setComponentAlignment(firstName, new Alignment(34));
		
		return firstNameDiv;
	}

	@AutoGenerated
	private HorizontalLayout buildLastNameDiv() {
		// common part: create layout
		lastNameDiv = new HorizontalLayout();
		lastNameDiv.setImmediate(false);
		lastNameDiv.setWidth("291px");
		lastNameDiv.setHeight("45px");
		lastNameDiv.setMargin(false);
		
		// lastNameLabel
		lastNameLabel = new Label();
		lastNameLabel.setStyleName("lastNameLabel");
		lastNameLabel.setImmediate(false);
		lastNameLabel.setWidth("69px");
		lastNameLabel.setHeight("60.0%");
		lastNameLabel.setValue("Last Name:");
		lastNameDiv.addComponent(lastNameLabel);
		lastNameDiv.setComponentAlignment(lastNameLabel, new Alignment(9));
		
		// lastName
		lastName = new TextField();
		lastName.setStyleName("lastName");
		lastName.setCaption("Last Name Required:");
		lastName.setImmediate(false);
		lastName.setWidth("202px");
		lastName.setHeight("20px");
		lastName.setRequired(true);
		lastName.setSecret(false);
		lastNameDiv.addComponent(lastName);
		lastNameDiv.setComponentAlignment(lastName, new Alignment(34));
		
		return lastNameDiv;
	}

	@AutoGenerated
	private HorizontalLayout buildConfirmDiv() {
		// common part: create layout
		confirmDiv = new HorizontalLayout();
		confirmDiv.setImmediate(false);
		confirmDiv.setWidth("100.0%");
		confirmDiv.setHeight("100.0%");
		confirmDiv.setMargin(false);
		
		// confirmLabel
		confirmLabel = new Label();
		confirmLabel.setImmediate(false);
		confirmLabel.setWidth("52px");
		confirmLabel.setHeight("-1px");
		confirmLabel.setValue("Confirm:");
		confirmDiv.addComponent(confirmLabel);
		confirmDiv.setComponentAlignment(confirmLabel, new Alignment(9));
		
		// passwordConfirm
		passwordConfirm = new PasswordField();
		passwordConfirm.setCaption("Need confirm password:");
		passwordConfirm.setImmediate(false);
		passwordConfirm.setWidth("195px");
		passwordConfirm.setHeight("20px");
		passwordConfirm.setRequired(true);
		confirmDiv.addComponent(passwordConfirm);
		confirmDiv.setExpandRatio(passwordConfirm, 1.0f);
		confirmDiv.setComponentAlignment(passwordConfirm, new Alignment(34));
		
		return confirmDiv;
	}

	@AutoGenerated
	private HorizontalLayout buildCompanyDiv() {
		// common part: create layout
		companyDiv = new HorizontalLayout();
		companyDiv.setImmediate(false);
		companyDiv.setWidth("299px");
		companyDiv.setHeight("31px");
		companyDiv.setMargin(false);
		
		// companyLabel
		companyLabel = new Label();
		companyLabel.setStyleName("companyLabel");
		companyLabel.setImmediate(false);
		companyLabel.setWidth("63px");
		companyLabel.setHeight("15px");
		companyLabel.setValue("Company:");
		companyDiv.addComponent(companyLabel);
		
		// company
		company = new TextField();
		company.setImmediate(false);
		company.setWidth("202px");
		company.setHeight("20px");
		company.setRequired(true);
		company.setSecret(false);
		companyDiv.addComponent(company);
		companyDiv.setComponentAlignment(company, new Alignment(34));
		
		return companyDiv;
	}

	@AutoGenerated
	private HorizontalSplitPanel buildForgotTab() {
		// common part: create layout
		forgotTab = new HorizontalSplitPanel();
		forgotTab.setImmediate(false);
		forgotTab.setWidth("100.0%");
		forgotTab.setHeight("100.0%");
		forgotTab.setMargin(false);
		
		// verticalLayout_1
		verticalLayout_1 = buildVerticalLayout_1();
		forgotTab.addComponent(verticalLayout_1);
		
		// forgotUserNameDiv
		forgotUserNameDiv = buildForgotUserNameDiv();
		forgotTab.addComponent(forgotUserNameDiv);
		
		return forgotTab;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_1() {
		// common part: create layout
		verticalLayout_1 = new VerticalLayout();
		verticalLayout_1.setImmediate(false);
		verticalLayout_1.setWidth("256px");
		verticalLayout_1.setHeight("128px");
		verticalLayout_1.setMargin(false);
		
		// forgotPasswordLabel2
		forgotPasswordLabel2 = new Label();
		forgotPasswordLabel2.setImmediate(false);
		forgotPasswordLabel2.setWidth("239px");
		forgotPasswordLabel2.setHeight("18px");
		forgotPasswordLabel2.setValue("Forgot Password? Type username below.");
		verticalLayout_1.addComponent(forgotPasswordLabel2);
		
		// userName
		userName = new TextField();
		userName.setCaption("Please type user name.");
		userName.setImmediate(false);
		userName.setWidth("219px");
		userName.setHeight("28px");
		userName.setRequired(true);
		userName.setSecret(false);
		verticalLayout_1.addComponent(userName);
		
		// sendReset
		sendReset = new Button();
		sendReset.setCaption("Send email");
		sendReset.setImmediate(true);
		sendReset.setWidth("199px");
		sendReset.setHeight("-1px");
		verticalLayout_1.addComponent(sendReset);
		
		return verticalLayout_1;
	}

	@AutoGenerated
	private VerticalLayout buildForgotUserNameDiv() {
		// common part: create layout
		forgotUserNameDiv = new VerticalLayout();
		forgotUserNameDiv.setImmediate(false);
		forgotUserNameDiv.setWidth("243px");
		forgotUserNameDiv.setHeight("128px");
		forgotUserNameDiv.setMargin(false);
		
		// forgotUserNameLabel
		forgotUserNameLabel = new Label();
		forgotUserNameLabel.setImmediate(false);
		forgotUserNameLabel.setWidth("-1px");
		forgotUserNameLabel.setHeight("-1px");
		forgotUserNameLabel.setValue("Forgot User name? Type email below.");
		forgotUserNameDiv.addComponent(forgotUserNameLabel);
		
		// forgotUserName
		forgotUserName = new TextField();
		forgotUserName.setStyleName("forgotUserName");
		forgotUserName.setCaption("Please type an email.");
		forgotUserName.setImmediate(false);
		forgotUserName.setWidth("203px");
		forgotUserName.setHeight("28px");
		forgotUserName.setRequired(true);
		forgotUserName.setSecret(false);
		forgotUserNameDiv.addComponent(forgotUserName);
		
		// sendEmail
		sendEmail = new Button();
		sendEmail.setCaption("Send email");
		sendEmail.setImmediate(true);
		sendEmail.setWidth("203px");
		sendEmail.setHeight("-1px");
		forgotUserNameDiv.addComponent(sendEmail);
		
		return forgotUserNameDiv;
	}

	

}
